apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: grafana
  namespace: monitoring
spec:
  virtualhost:
    fqdn: grafana.event.cloudopsdays.jp
    tls:
      secretName: cert-manager/wildcard-cloudopsdays-jp
  routes:
  - services:
      - name: grafana
        port: 80
