apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- secret.yaml
- ingress.yaml
- redis.yaml
- hpa.yaml
- ../../../base/
- deployment-fifo-worker.yaml
patchesStrategicMerge:
- deployment-dreamkast.yaml
namespace: dreamkast-staging
images:
- name: public.ecr.aws/q5p7z1m4/dreamkast-ecs
  newTag: af43ba58a88b17b89d65df6a09300e3998a31168
- name: public.ecr.aws/q5p7z1m4/dreamkast-ui
  newTag: e83f415a4828ceb06e868dfc5cbdaa8119599b04
