apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- secret.yaml
- ingress.yaml
- redis.yaml
- hpa.yaml
- ../../../base/
- deployment-fifo-worker.yaml
patchesStrategicMerge:
- deployment-dreamkast.yaml
namespace: dreamkast-staging
images:
- name: public.ecr.aws/q5p7z1m4/dreamkast-ecs
  newTag: ead6a30b3f080403189c4aeaf26557d1e526267d
- name: public.ecr.aws/q5p7z1m4/dreamkast-ui
  newTag: 68ca09b0ff420848b0a9f72bb9e33352cea98991
