apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- secret.yaml
- ingress.yaml
- redis.yaml
- hpa.yaml
- ../../../base/
- deployment-fifo-worker.yaml
patchesStrategicMerge:
- deployment-dreamkast.yaml
namespace: dreamkast-staging
images:
- name: public.ecr.aws/q5p7z1m4/dreamkast-ecs
  newTag: 1d38e4383b1b90703b554d68e339ddfda10f32ca
- name: public.ecr.aws/q5p7z1m4/dreamkast-ui
  newTag: e83f415a4828ceb06e868dfc5cbdaa8119599b04
