apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- secret.yaml
- ingress.yaml
- redis.yaml
- hpa.yaml
- ../../../base/
- deployment-fifo-worker.yaml
patchesStrategicMerge:
- deployment-dreamkast-production.yaml
namespace: dreamkast-staging
images:
- name: 632965872029.dkr.ecr.ap-northeast-1.amazonaws.com/dreamkast-ecs
  newTag: fade8e8a31d184c5446a88f474e7522fc06bcd5b
- name: 632965872029.dkr.ecr.ap-northeast-1.amazonaws.com/dreamkast-ui
  newTag: ae7a5746936cc20b7858f38dc8f12ea0ecb1595f
