apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- secret.yaml
- ingress.yaml
- redis.yaml
- hpa.yaml
- ../../../base/
- deployment-fifo-worker.yaml
patchesStrategicMerge:
- deployment-dreamkast.yaml
namespace: dreamkast-staging
images:
- name: 632965872029.dkr.ecr.ap-northeast-1.amazonaws.com/dreamkast-ecs
  newTag: a8fedbad2c0ec86d80adfddd1f0e657751ecc2a8
- name: 632965872029.dkr.ecr.ap-northeast-1.amazonaws.com/dreamkast-ui
  newTag: ae7a5746936cc20b7858f38dc8f12ea0ecb1595f
