apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    dreamkast.cloudnativedays.jp/app-commit-hash: 71d240ae0646c6d0f70860562e85c06d26d78f01
    dreamkast.cloudnativedays.jp/app-organization: cloudopsdays
    dreamkast.cloudnativedays.jp/app-repository: dreamkast_codt2022
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: dreamkast-development-dk-codt2022-60
  namespace: argocd
spec:
  destination:
    namespace: dreamkast-dk-codt2022-60
    server: https://kubernetes.default.svc
  project: app
  source:
    path: manifests/app/dreamkast/overlays/development/dk-codt2022-60
    repoURL: https://github.com/cloudopsdays/dreamkast-infra_codt2022
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
