apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    dreamkast.cloudnativedays.jp/app-commit-hash: 497f4d336e480a1db62603cf6b0d3af88296005a
    dreamkast.cloudnativedays.jp/app-organization: cloudopsdays
    dreamkast.cloudnativedays.jp/app-repository: dreamkast_codt2022
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: dreamkast-development-dk-codt2022-51
  namespace: argocd
spec:
  destination:
    namespace: dreamkast-dk-codt2022-51
    server: https://kubernetes.default.svc
  project: app
  source:
    path: manifests/app/dreamkast/overlays/development/dk-codt2022-51
    repoURL: https://github.com/cloudopsdays/dreamkast-infra_codt2022
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
