AWSTemplateFormatVersion: "2010-09-09"
Description:
  Dreamkast test S3
Parameters:
  PJPrefix:
    Type: String
    Default: "dreamkast-codt"
  S3BucketName:
    Type: String
    Default: "bucket"
Resources:

# ------------------------------------------------------------#
# S3 Bucket
# ------------------------------------------------------------#

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${PJPrefix}-${S3BucketName}"
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True

# ------------------------------------------------------------#
# Output Parameters
# ------------------------------------------------------------#
Outputs:
#S3BucketName
  S3BucketName:
    Value: !Ref S3Bucket
    Export:
      Name: !Sub "${PJPrefix}-bucket-id"
