apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dreamkast-dk-codt2022-48
bases:
- ../../../base
resources:
- ns.yaml
- mysql.yaml
- redis.yaml
- externalsecret.yaml
- ingress.yaml
- viewer-count.yaml
- polling-harvest-job-and-update-video.yaml
- deployment-fifo-worker.yaml
patchesStrategicMerge:
- deployment-dreamkast.yaml
images:
- name: "public.ecr.aws/q5p7z1m4/dreamkast-ecs"
  newTag: "15f795d3e071d9ff8e88d5f9f49cec0ce23ed5b1"
