
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dreamkast
    tier: dreamkast-fifo-worker
  name: dreamkast-fifo-worker
spec:
  selector:
    matchLabels:
      app: dreamkast
      tier: dreamkast-fifo-worker
  template:
    metadata:
      labels:
        app: dreamkast
        tier: dreamkast-fifo-worker
    spec:
      containers:
      - name: dreamkast
        image: public.ecr.aws/q5p7z1m4/dreamkast-ecs:main
        imagePullPolicy: Always
        args:
          - exec
          - rake
          - aws_sqs:fifo_job
        command:
          - bundle
        env:
        - name: RAILS_ENV
          value: "production"
        - name: MYSQL_HOST
          value: "dreamkast-codt-rds.cysvpzying2j.ap-northeast-1.rds.amazonaws.com"
        - name: MYSQL_DATABASE
          value: "dreamkast"
        - name: REDIS_URL
          value: "redis://dreamkast-redis:6379"
        - name: SENTRY_DSN
          value: ""
        - name: S3_BUCKET
          value: "dreamkast-codt-bucket-production"
        - name: S3_REGION
          value: ap-northeast-1
        - name: AWS_REGION
          value: ap-northeast-1
        - name: SQS_FIFO_QUEUE_URL
          value: "https://sqs.ap-northeast-1.amazonaws.com/632965872029/dreamkast-codtFifoQueue.fifo"
        - name: DREAMKAST_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: RAILS_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: rails-app-secret
              key: rails-app-secret
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        - name: AUTH0_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: dreamkast-secret
              key: AUTH0_CLIENT_ID
        - name: AUTH0_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: dreamkast-secret
              key: AUTH0_CLIENT_SECRET
        - name: AUTH0_DOMAIN
          valueFrom:
            secretKeyRef:
              name: dreamkast-secret
              key: AUTH0_DOMAIN
