apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- secret.yaml
- ingress.yaml
- redis.yaml
- hpa.yaml
- ../../../base/
- deployment-fifo-worker.yaml
patchesStrategicMerge:
- deployment-dreamkast.yaml
namespace: dreamkast
images:
- name: public.ecr.aws/q5p7z1m4/dreamkast-ecs
  newTag: 4a68fc0ca0380e59703e01323990a132121ac223
- name: public.ecr.aws/q5p7z1m4/dreamkast-ui
  newTag: e02c40c95bc328ebcb22f96b1748e96e10b5ea3d
