apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- secret.yaml
- ingress.yaml
- redis.yaml
- hpa.yaml
- ../../../base/
- deployment-fifo-worker.yaml
patchesStrategicMerge:
- deployment-dreamkast.yaml
namespace: dreamkast
images:
- name: public.ecr.aws/q5p7z1m4/dreamkast-ecs
  newTag: a1869a3450828b8b8fd13f23dd94c0109406d22f
- name: public.ecr.aws/q5p7z1m4/dreamkast-ui
  newTag: b73ff03bfd9076d57216de3c537ff8b5949e4e56
