apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- secret.yaml
- ingress.yaml
- redis.yaml
- hpa.yaml
- ../../../base/
- deployment-fifo-worker.yaml
patchesStrategicMerge:
- deployment-dreamkast.yaml
namespace: dreamkast
images:
- name: public.ecr.aws/q5p7z1m4/dreamkast-ecs
  newTag: e764184cc26572cd6de6af1bbca4d36f945cef7d
- name: public.ecr.aws/q5p7z1m4/dreamkast-ui
  newTag: 3e4c03d0473788537912fe1986f02468808790c0
