---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: db-secret
spec:
  backendType: secretsManager
  data:
    - key: MyRDSSecret-zDVO0yp28g9P
      name: password
      property: password
    - key: MyRDSSecret-zDVO0yp28g9P
      name: username
      property: username
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: dreamkast-secret
spec:
  backendType: secretsManager
  data:
    - key: dreamkast/production-env
      name: AUTH0_CLIENT_ID
      property: AUTH0_CLIENT_ID
    - key: dreamkast/production-env
      name: AUTH0_CLIENT_SECRET
      property: AUTH0_CLIENT_SECRET
    - key: dreamkast/production-env
      name: AUTH0_DOMAIN
      property: AUTH0_DOMAIN
