apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dreamkast-ui-codt2022-1
bases:
- ../../../base
resources:
- ns.yaml
- mysql.yaml
- redis.yaml
- externalsecret.yaml
- ingress.yaml
- viewer-count.yaml
- polling-harvest-job-and-update-video.yaml
- deployment-fifo-worker.yaml
patchesStrategicMerge:
- deployment-dreamkast.yaml
images:
- name: "632965872029.dkr.ecr.ap-northeast-1.amazonaws.com/dreamkast-ui"
  newTag: "cf5743d047e41f0603622ee2fff90b22c1a366e5"
