apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dreamkast-dk-codt2022-11
bases:
- ../../../base
resources:
- ns.yaml
- mysql.yaml
- redis.yaml
- externalsecret.yaml
- ingress.yaml
- viewer-count.yaml
- polling-harvest-job-and-update-video.yaml
- deployment-fifo-worker.yaml
patchesStrategicMerge:
- deployment-dreamkast.yaml
images:
- name: "632965872029.dkr.ecr.ap-northeast-1.amazonaws.com/dreamkast-ecs"
  newTag: "6ec34f7da99dc06cf6ac98753d45f99eb1d47071"
