apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: argocd-server-grpc
  namespace: argocd
spec:
  virtualhost:
    fqdn: argocd.event.cloudopsdays.com
    tls:
      secretName: cert-manager/wildcard-cloudopsdays-jp
  routes:
  - services:
    - name: argocd-server
      port: 80
