apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dreamkast-ui-codt2022-10
bases:
- ../../../base
resources:
- ns.yaml
- mysql.yaml
- redis.yaml
- externalsecret.yaml
- ingress.yaml
- viewer-count.yaml
- polling-harvest-job-and-update-video.yaml
- deployment-fifo-worker.yaml
patchesStrategicMerge:
- deployment-dreamkast.yaml
images:
- name: "public.ecr.aws/q5p7z1m4/dreamkast-ui"
  newTag: "21a979d5d9e0420e5d36da7adf0e6f0e913fea7e"
