apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dreamkast-ui-codt2022-13
bases:
- ../../../base
resources:
- ns.yaml
- mysql.yaml
- redis.yaml
- externalsecret.yaml
- ingress.yaml
- viewer-count.yaml
- polling-harvest-job-and-update-video.yaml
- deployment-fifo-worker.yaml
patchesStrategicMerge:
- deployment-dreamkast.yaml
images:
- name: "public.ecr.aws/q5p7z1m4/dreamkast-ui"
  newTag: "f72626fb48793de5e437836a81956f6d8aae7e3a"
