apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dreamkast-production-main
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # cascade deletion on this App deletion
  annotations:
    argocd-image-updater.argoproj.io/image-list: >
      dreamkast=public.ecr.aws/q5p7z1m4/dreamkast-ecs
    argocd-image-updater.argoproj.io/dreamkast.update-strategy: latest
    argocd-image-updater.argoproj.io/dreamkast.allow-tags: regexp:^main-.*$
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/write-back-target: kustomization:../../dreamkast/overlays/production/main
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  destination:
    namespace: dreamkast
    server: https://kubernetes.default.svc
  project: app
  source:
    path: manifests/app/dreamkast/overlays/production/main
    repoURL: https://github.com/cloudopsdays/dreamkast-infra_codt2022.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
